name: Docker for controller-layer
on:
  push:
    branches: [ master ]
    paths:
      - 'base-images/controller-layer/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'base-images/controller-layer/**'
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Docker Build
        shell: bash
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          DOCKER_BUILDKIT=1 docker buildx build base-images/controller-layer/ -t ghcr.io/dkoch84/controller-layer:$(date +%Y%m%d.$GITHUB_RUN_NUMBER) -t ghcr.io/dkoch84/controller-layer:latest
          docker images
      - name: Docker Push
        shell: bash
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u dkoch84 --password-stdin
          docker push -a ghcr.io/dkoch84/controller-layer
